import type { Alert, Case } from '@/types/domain'
import { STRATHMORE } from '@/theme/strathmore'

export function exportShiftBrief({
  generatedBy,
  notes,
  alerts,
  cases,
}: {
  generatedBy: string
  notes: string
  alerts: Alert[]
  cases: Case[]
}) {
  if (typeof window === 'undefined') {
    return
  }

  const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>NOVA Shift Brief</title>
    <style>
      body { font-family: Arial, sans-serif; margin: 32px; color: ${STRATHMORE.ink}; background: ${STRATHMORE.offwhite}; }
      h1, h2 { margin-bottom: 8px; color: ${STRATHMORE.blue}; }
      .meta, .chip { font-size: 12px; text-transform: uppercase; letter-spacing: 0.12em; }
      .meta { color: ${STRATHMORE.muted}; }
      .chip { display: inline-block; border: 1px solid ${STRATHMORE.gold}; background: ${STRATHMORE.white}; color: ${STRATHMORE.blue}; padding: 6px 10px; margin-right: 8px; margin-bottom: 8px; }
      .card { border: 1px solid ${STRATHMORE.border}; background: ${STRATHMORE.white}; padding: 16px; margin-bottom: 12px; }
      ul { padding-left: 18px; }
    </style>
  </head>
  <body>
    <p class="meta">NOVA / Strathmore Security Operations / DAMA LTD</p>
    <h1>Shift Handover Brief</h1>
    <p>Generated by ${generatedBy} on ${new Date().toLocaleString()}</p>
    <div>
      <span class="chip">Biometrics disabled</span>
      <span class="chip">Snapshots + metadata only</span>
      <span class="chip">Human validation required</span>
    </div>
    <h2>Shift Notes</h2>
    <div class="card">${notes ? notes.replace(/\n/g, '<br />') : 'No shift notes recorded.'}</div>
    <h2>Open Queue</h2>
    ${alerts
      .map(
        (alert) => `<div class="card"><strong>${alert.title}</strong><br />${alert.zone} / ${alert.severity} / ${alert.status}<br />${alert.summary}</div>`,
      )
      .join('') || '<div class="card">No open alerts.</div>'}
    <h2>Active Cases</h2>
    ${cases
      .map(
        (caseItem) => `<div class="card"><strong>${caseItem.title}</strong><br />${caseItem.location} / ${caseItem.status}<br />${caseItem.protocol}</div>`,
      )
      .join('') || '<div class="card">No active cases.</div>'}
  </body>
</html>`

  const popup = window.open('', '_blank', 'noopener,noreferrer,width=1024,height=768')
  if (!popup) {
    return
  }

  popup.document.open()
  popup.document.write(html)
  popup.document.close()
}
