const brand = {
  gold: '#CBA052',
  blue: '#3A5DAE',
  red: '#E03C31',
} as const

const neutral = {
  white: '#FFFFFF',
  ink: '#152033',
  slate950: '#0F1726',
  slate900: '#162033',
  slate800: '#213049',
  slate700: '#43506A',
  slate500: '#65728A',
  slate300: '#C8D0DE',
  slate200: '#D8DFEA',
  slate100: '#E8EDF5',
  warm50: '#F6F4EE',
  warm100: '#FCFAF6',
  warm200: '#F7F2E8',
  warm300: '#EFE7D8',
  warm400: '#D8CFBF',
} as const

const semantic = {
  background: neutral.warm50,
  foreground: neutral.ink,
  card: neutral.warm100,
  cardForeground: neutral.ink,
  popover: neutral.warm100,
  popoverForeground: neutral.ink,
  primary: brand.blue,
  primaryForeground: neutral.white,
  secondary: neutral.slate100,
  secondaryForeground: neutral.ink,
  muted: '#ECE7DC',
  mutedForeground: '#5F6776',
  accent: brand.blue,
  accentForeground: neutral.white,
  destructive: brand.red,
  border: neutral.warm400,
  input: '#E5DECF',
  ring: brand.blue,
  chart1: brand.blue,
  chart2: brand.gold,
  chart3: '#5F7EBA',
  chart4: brand.red,
  chart5: '#6B7892',
  sidebarBg: neutral.slate950,
  sidebarForeground: '#F7F8FB',
  sidebarPrimary: brand.gold,
  sidebarPrimaryForeground: neutral.slate950,
  sidebarAccent: '#17243B',
  sidebarAccentForeground: '#F7F8FB',
  sidebarActive: '#223A68',
  sidebarActiveForeground: '#F7F8FB',
  sidebarBorder: '#2D3A55',
  sidebarRing: brand.blue,
  sidebarBadge: 'rgba(203, 160, 82, 0.12)',
  panel: neutral.warm200,
  panelStrong: neutral.warm300,
  panelDark: '#121D2F',
  panelDarkForeground: '#F7F8FB',
  link: brand.blue,
  linkHover: brand.gold,
  signalCritical: brand.red,
  signalHigh: brand.gold,
  signalMedium: brand.blue,
  signalLow: '#677790',
  severityCriticalBg: '#FCE4E2',
  severityCriticalBorder: '#F0B0AA',
  severityCriticalForeground: '#7A231C',
  severityHighBg: '#F6EFD9',
  severityHighBorder: '#D9B870',
  severityHighForeground: '#5E471D',
  severityMediumBg: '#E7EEF9',
  severityMediumBorder: '#91A9D8',
  severityMediumForeground: '#24437F',
  severityLowBg: '#EEF2F7',
  severityLowBorder: '#BCC5D3',
  severityLowForeground: '#415066',
  statusInfoBg: '#E7EEF9',
  statusInfoBorder: '#91A9D8',
  statusInfoForeground: '#24437F',
  statusMutedBg: '#F2ECE0',
  statusMutedBorder: '#D2C5AB',
  statusMutedForeground: '#604F30',
  statusSuccessBg: '#E6F1EB',
  statusSuccessBorder: '#A7C5B4',
  statusSuccessForeground: '#2D5440',
  noticeBg: '#F9F1DD',
  noticeBorder: '#D6B06A',
  noticeForeground: '#60491D',
} as const

export const themeTokens = {
  brand,
  neutral,
  semantic,
} as const

export const rootColorVariables = {
  '--brand-gold': brand.gold,
  '--brand-blue': brand.blue,
  '--brand-red': brand.red,
  '--neutral-white': neutral.white,
  '--neutral-ink': neutral.ink,
  '--neutral-slate-950': neutral.slate950,
  '--neutral-slate-900': neutral.slate900,
  '--neutral-slate-800': neutral.slate800,
  '--neutral-slate-700': neutral.slate700,
  '--neutral-slate-500': neutral.slate500,
  '--neutral-slate-300': neutral.slate300,
  '--neutral-slate-200': neutral.slate200,
  '--neutral-slate-100': neutral.slate100,
  '--neutral-warm-50': neutral.warm50,
  '--neutral-warm-100': neutral.warm100,
  '--neutral-warm-200': neutral.warm200,
  '--neutral-warm-300': neutral.warm300,
  '--neutral-warm-400': neutral.warm400,
  '--brand-accent': semantic.accent,
  '--brand-accent-foreground': semantic.accentForeground,
  '--background': semantic.background,
  '--foreground': semantic.foreground,
  '--card': semantic.card,
  '--card-foreground': semantic.cardForeground,
  '--popover': semantic.popover,
  '--popover-foreground': semantic.popoverForeground,
  '--primary': semantic.primary,
  '--primary-foreground': semantic.primaryForeground,
  '--secondary': semantic.secondary,
  '--secondary-foreground': semantic.secondaryForeground,
  '--muted': semantic.muted,
  '--muted-foreground': semantic.mutedForeground,
  '--accent': semantic.accent,
  '--accent-foreground': semantic.accentForeground,
  '--destructive': semantic.destructive,
  '--border': semantic.border,
  '--input': semantic.input,
  '--ring': semantic.ring,
  '--chart-1': semantic.chart1,
  '--chart-2': semantic.chart2,
  '--chart-3': semantic.chart3,
  '--chart-4': semantic.chart4,
  '--chart-5': semantic.chart5,
  '--sidebar-bg': semantic.sidebarBg,
  '--sidebar-foreground': semantic.sidebarForeground,
  '--sidebar-primary': semantic.sidebarPrimary,
  '--sidebar-primary-foreground': semantic.sidebarPrimaryForeground,
  '--sidebar-accent': semantic.sidebarAccent,
  '--sidebar-accent-foreground': semantic.sidebarAccentForeground,
  '--sidebar-active': semantic.sidebarActive,
  '--sidebar-active-foreground': semantic.sidebarActiveForeground,
  '--sidebar-border': semantic.sidebarBorder,
  '--sidebar-ring': semantic.sidebarRing,
  '--sidebar-badge': semantic.sidebarBadge,
  '--sidebar': semantic.sidebarBg,
  '--panel': semantic.panel,
  '--panel-strong': semantic.panelStrong,
  '--panel-dark': semantic.panelDark,
  '--panel-dark-foreground': semantic.panelDarkForeground,
  '--link': semantic.link,
  '--link-hover': semantic.linkHover,
  '--signal-critical': semantic.signalCritical,
  '--signal-high': semantic.signalHigh,
  '--signal-medium': semantic.signalMedium,
  '--signal-low': semantic.signalLow,
  '--severity-critical-bg': semantic.severityCriticalBg,
  '--severity-critical-border': semantic.severityCriticalBorder,
  '--severity-critical-fg': semantic.severityCriticalForeground,
  '--severity-high-bg': semantic.severityHighBg,
  '--severity-high-border': semantic.severityHighBorder,
  '--severity-high-fg': semantic.severityHighForeground,
  '--severity-medium-bg': semantic.severityMediumBg,
  '--severity-medium-border': semantic.severityMediumBorder,
  '--severity-medium-fg': semantic.severityMediumForeground,
  '--severity-low-bg': semantic.severityLowBg,
  '--severity-low-border': semantic.severityLowBorder,
  '--severity-low-fg': semantic.severityLowForeground,
  '--status-info-bg': semantic.statusInfoBg,
  '--status-info-border': semantic.statusInfoBorder,
  '--status-info-fg': semantic.statusInfoForeground,
  '--status-muted-bg': semantic.statusMutedBg,
  '--status-muted-border': semantic.statusMutedBorder,
  '--status-muted-fg': semantic.statusMutedForeground,
  '--status-success-bg': semantic.statusSuccessBg,
  '--status-success-border': semantic.statusSuccessBorder,
  '--status-success-fg': semantic.statusSuccessForeground,
  '--notice-bg': semantic.noticeBg,
  '--notice-border': semantic.noticeBorder,
  '--notice-foreground': semantic.noticeForeground,
} as const

export function applyThemeTokens(root: HTMLElement = document.documentElement) {
  for (const [name, value] of Object.entries(rootColorVariables)) {
    root.style.setProperty(name, value)
  }
}
